[package]
name = "unimpaired_cairo"
version = "0.5.0"
license-file = "LICENSE"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifes

[[target.starknet-contract]]
sierra = true
casm=false


[dependencies]
openzeppelin_token = "0.20.0"
openzeppelin_account = "0.20.0"
openzeppelin_introspection = "0.20.0"
openzeppelin_upgrades = "0.20.0"
starknet = "2.11.0"

[dev-dependencies]
snforge_std = "0.38.3"

[cairo]
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true
inlining-strategy = "avoid"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
