name: snforge test
on:
  push:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.9.1"
      - uses: foundry-rs/setup-snfoundry@v3
        with:
          starknet-foundry-version: "0.34.0"
      - run: snforge test
